INSERT INTO Vocabularies (Name, Pronunciation, Meaning, TopicId) VALUES (N'cat', N'/kæt/', N'mèo', 1),
(N'kitten', N'/ˈkɪt.ən/', N'mèo con', 1),
(N'dog', N'/dɒg/', N'chó', 1),
(N'bitch', N'/bɪtʃ/', N'chó cái', 1),
(N'puppy', N'/ˈpʌp.i/', N'chó con', 1),
(N'parrot', N'/’pærət/', N'con vẹt', 1),
(N'gecko', N'/’gekou/', N'con tắc kè', 1),
(N'chinchilla', N'/tʃin’tʃilə/', N'sóc sinsin (ở nam-mỹ)', 1),
(N'dalmatian', N'/dælˈmeɪʃən/', N'chó đốm', 1),
(N'guinea pig', N'/ˈgɪni pig/', N'chuột lang', 1),
(N'hamste', N'/’hæmstə/', N'r  chuột đồng', 1),
(N'rabbit', N'/’ræbit/', N'thỏ', 1),
(N'bird', N'/bəd/', N': chim', 1),
(N'ferret', N'/’ferit/', N'chồn furô', 1),
(N'betta fish', N'/ˈbɛtə fiʃ/', N'(fighting fish)  cá chọi', 1),
(N'bird', N'', N'các loài chim nói chung', 2),
(N'pheasant', N'/ˈfɛznt/', N'gà lôi', 2),
(N'swallow', N'/ˈswɒləʊ/', N'chim én', 2),
(N'canary', N'/kəˈneəri/', N'chim hoàng yến', 2),
(N'pigeon', N'/ˈpɪʤɪn/', N'chim bồ câu', 2),
(N'parrot', N'/ˈpærət/', N'vẹt', 2),
(N'crow', N'/krəʊ/', N'quạ', 2),
(N'hummingbird', N'/ˈhʌmɪŋbɜːd/', N'chim ruồi', 2),
(N'raven', N'/ˈreɪvn/', N'quạ', 2),
(N'quail', N'/kweɪl/', N'chim cút', 2),
(N'kingfisher', N'/ˈkɪŋˌfɪʃə/', N'chim bói cá', 2),
(N'swan', N'/swɒn/', N'thiên nga', 2),
(N'woodpecker', N'/ˈwʊdˌpɛkə/', N'chim gõ kiến', 2),
(N'toucan', N'/ˈtuːkən/', N'chim toucan', 2),
(N'sparrow', N'/ˈspærəʊ/', N'chim sẻ', 2),
(N'peacock', N'/ˈpiːkɒk/', N'công', 2),
(N'pengui', N'/ˈpɛŋgwɪn/', N'n  chim cánh cụt', 2),
(N'ostrich', N'/ˈɒstrɪʧ/', N'đà điểu', 2),
(N'seagull', N'/ˈsiːgʌl/', N'chim mòng biển', 2),
(N'eagle', N'/ˈiːgl/', N'đại bàng', 2),
(N'flamingo', N'/fləˈmɪŋgəʊ/', N'hồng hạc', 2),
(N'hawk', N'/hɔːk/', N'diều hâu', 2),
(N'stork', N'/stɔːk/', N'cò', 2),
(N'falcon', N'/ˈfɔːlkən/', N'chim ưng', 2),
(N'vulture', N'/ˈvʌlʧə/', N'kền kền', 2),
(N'hawk', N'/hɔk/', N'diều hâu, chim ưng', 2),
(N'hen', N'/hen/', N'gà mái', 2),
(N'hummingbird', N'/’hʌmiɳ /bəd/', N'chim ruồi', 2),
(N'ostrich', N'/’ɔstritʃ/', N'đà điểu châu phi', 2),
(N'owl', N'/aul/', N'chim cú', 2),
(N'parrot', N'/’pærət/', N'chim vẹt', 2),
(N'peacock', N'/’pikɔk/', N'chim công', 2),
(N'pelican', N'/’pelikən/', N'chim bồ nông', 2),
(N'petrel', N'/’petrəl/', N'hải âu pê-tren (loại nhỏ)', 2),
(N'crab', N'/kræb/', N'cua', 3),
(N'seal', N'/siːl/', N'hải cẩu', 3),
(N'octopus', N'/ˈɒktəpəs/', N'bạch tuộc', 3),
(N'shark', N'/ʃɑːk/', N'cá mập', 3),
(N'seahorse', N'/ˈsiːhɔːs/', N'cá ngựa', 3),
(N'walrus', N'/ˈwɔːlrəs/', N'voi biển', 3),
(N'starfish', N'/ˈstɑːfɪʃ/', N'sao biển', 3),
(N'whale', N'/weɪl/', N'cá voi', 3),
(N'penguin', N'/ˈpɛŋgwɪn/', N'chim cánh cụt', 3),
(N'squid', N'/skwɪd/', N'con mực', 3),
(N'lobster', N'/ˈlɒbstə/', N'tôm hùm', 3),
(N'shrimp', N'/ʃrɪmp/', N'tôm', 3),
(N'coral', N'/ˈkɒrəl/', N'san hô', 3),
(N'seaweed', N'/ˈsiːwiːd/', N'rong biển', 3),
(N'clam', N'/klæmz/', N'con nghêu', 3),
(N'sentinel crab', N'/ˈsɛntɪnl kræb/', N'con ghẹ', 3),
(N'dolphin', N'/ˈdɒlfɪn/', N'cá heo', 3),
(N'mussel', N'/ˈmʌsl/', N'con trai', 3),
(N'oyster', N'/ˈɔɪstə/', N'con hàu', 3),
(N'scallop', N'/ˈskɒləp/', N'sò điệp', 3),
(N'goldfish', N'/ˈgəʊldfɪʃ/', N'cá vàng', 3),
(N'salmon', N'/ˈsæmən/', N'cá hồi', 3),
(N'sea snail', N'/siː/ /sneɪl/', N'ốc biển', 3),
(N'sea urchin', N'/siː/ /ˈɜːʧɪn/', N'nhím biển', 3),
(N'sea turtle', N'/siː/ /ˈtɜːtl/', N'rùa biển', 3),
(N'sea lion', N'/siː/ /ˈlaɪən/', N'sư tử biển', 3),
(N'salamander', N'/ˈsæləˌmændə/', N'kỳ giông', 3),
(N'hippopotamus', N'/ˌhɪpəˈpɒtəməs/', N'hà mã', 3),
(N'fish', N'/fɪʃ/', N'cá', 3),
(N'clownfish', N'/ˈklaʊnfɪʃ/', N'cá hề', 3),
(N'common carp', N'/ˈkɒmən kɑːp/', N'cá chép', 3),
(N'crocodile', N'/ˈkrɒkədaɪl/', N'cá sấu', 3),
(N'anchovy', N'/ˈænʧəvi/', N'cá cơm biển', 3),
(N'sperm whale', N'/spɜːm weɪl/', N'cá nhà táng', 3),
(N'catfish', N'/ˈkætˌfɪʃ/', N'cá trê', 3),
(N'mackerel', N'/ˈmækrəl/', N'cá thu', 3),
(N'pomfret', N'/ˈpɒmfrɪt/', N'cá chim', 3),
(N'eel', N'/iːl/', N'lươn', 3),
(N'flounder', N'/ˈflaʊndə/', N'cá bơn', 3),
(N'goby', N'/ˈɡəʊbi/', N'cá bống', 3),
(N'herring', N'/ˈhɛrɪŋ/', N'cá trích', 3),
(N'catfish', N'/ˈkætfɪʃ/', N'cá trê', 3),
(N'tench', N'/tentʃ/', N'cá mè', 3),
(N'tilapia', N'/tɪˈlɑːpiə/', N'cá rô', 3),
(N'pufferfis', N'/ˈpʌfəfɪʃ/', N'h  cá nóc', 3),
(N'suckermouth catfish', N'/ˈsʌkəmaʊθ ˈkatfɪʃ/', N'cá dọn bể', 3),
(N'red tilapia', N'/rɛd tɪˈleɪpɪə/', N'cá diêu hồng', 3),
(N'swordfish', N'/ˈsɔːdfɪʃ/', N'cá kiếm', 3),
(N'stingray', N'/ˈstɪŋreɪ/', N'cá đuối', 3),
(N'tuna', N'/ˈtjuːnə/', N'cá ngừ', 3),
(N'anabas', N'/ˈanəbəs/', N'cá rô', 3),
(N'flowerhorn', N'/ˈflaʊəhɔːn/', N'cá la hán', 3),
(N'sardine', N'/sɑːˈdiːn/', N'cá mòi', 3),
(N'snakehead fish', N'/ˈsneɪkhɛd fɪʃ/', N'cá quả', 3),
(N'angelfish', N'/ˈeɪndʒ(ə)lfɪʃ/', N'cá thiên thần', 3),
(N'alligator', N'/ˈælɪgeɪtə/', N'cá sấu mỹ', 3),
(N'sea snake', N'/siː sneɪk/', N'rắn biển', 3),
(N'frog', N'/frɒg/', N'ếch', 3),
(N'jellyfish', N'/ˈdʒel.i.fɪʃ/', N'con sứa', 3),
(N'killer whale', N'/ˈkɪl.əʳ weɪl/', N'loại cá voi nhỏ màu đen trắng', 3),
(N'seal', N'/siːl/', N'chó biển', 3),
(N'squid', N'/skwɪd/', N'mực ống', 3),
(N'bear', N'/beə/', N'gấu', 4),
(N'polar bear', N'/ˈpəʊlə beə/', N'gấu bắc cực', 4),
(N'panda', N'/ˈpændə/', N'gấu trúc', 4),
(N'tiger cub', N'/ˈtaɪgə kʌb/', N'hổ con', 4),
(N'lion', N'/ˈlaɪən/', N'sư tử', 4),
(N'lioness', N'/ˈlaɪənes/', N'sư tử cái', 4),
(N'lion cu', N'/ˈlaɪən kʌb/', N'b   sư tử con', 4),
(N'tiger', N'/ˈtaɪgə/', N'hổ', 4),
(N'tigress', N'/ˈtaɪɡrəs/', N'hổ cái', 4),
(N'panther', N'/ˈpænθə/', N'báo đen', 4),
(N'leopar', N'/ˈlɛpəd/', N'd  báo đốm', 4),
(N'cheeta', N'/ˈʧiːtə/', N'h  báo ghê.ta', 4),
(N'gazelle', N'/ɡəˈzel/', N'linh dương', 4),
(N'rhinocero', N'/raɪˈnɒsərəs/', N's  tê giác', 4),
(N'fox', N'/fɒks/', N'cáo', 4),
(N'fawn', N'/fɔːn/', N'nai con', 4),
(N'reindeer', N'/ˈreɪndɪə/', N'tuần lộc', 4),
(N'elk', N'/ɛlk/', N'nai sừng tấm', 4),
(N'moose', N'/muːs/', N'nai sừng tấm', 4),
(N'ra', N'/ræt/', N't  chuột', 4),
(N'elephant', N'/ˈɛlɪfənt/', N'voi', 4),
(N'wolf', N'/wʊlf/', N'sói', 4),
(N'deer', N'/dɪə/', N'nai', 4),
(N'doe', N'/dəʊ/', N'con nai cái', 4),
(N'giraffe', N'/ʤɪˈrɑːf/', N'hươu cao cổ', 4),
(N'frog /frɒg/ ếch', N'/frɒg/', N'ếch', 4),
(N'snake', N'/sneɪk/', N'rắn', 4),
(N'alligator', N'/ˈælɪgeɪtə/', N'cá sấu', 4),
(N'crocodile', N'/ˈkrɒkədaɪl/', N'cá sấu', 4),
(N'bat', N'/bæt/', N'dơi', 4),
(N'gorilla', N'/gəˈrɪlə/', N'gô ri la', 4),
(N'giant panda', N'/ˈʤaɪənt ˈpændə/', N'gấu trúc', 4),
(N'boar', N'/bɔː/', N'lợn rừng', 4),
(N'koala', N'/kəʊˈɑːlə/', N'koala', 4),
(N'camel', N'/ˈkæməl/', N'lạc đà', 4),
(N'sloth', N'/sləʊθ/', N'con lười', 4),
(N'hyena/', N'', N'haɪˈiːnə linh cẩu', 4),
(N'chimpanzee', N'/ˌʧɪmpənˈziː/', N'tinh tinh', 4),
(N'zebra', N'/ˈziːbrə/', N'ngựa vằn', 4),
(N'squirrel', N'/ˈskwɪrəl/', N'sóc', 4),
(N'baboon', N'/bəˈbuːn/', N'khỉ đầu chó', 4),
(N'monkey', N'/ˈmʌŋki/', N'khỉ', 4),
(N'racoon', N'/rəˈkuːn/', N'gấu mèo', 4),
(N'platypus', N'/ˈplætɪpəs/', N'thú mỏ vịt', 4),
(N'otter', N'/ˈɒtə/', N'rái cá', 4),
(N'skunk', N'/skʌŋk/', N'chồn hôi', 4),
(N'chimpanzee', N'/ˌʧɪmpənˈziː/', N'con hắc tinh tinh', 4),
(N'badger', N'/ˈbæʤə/', N'con lửng', 4),
(N'weasel', N'/ˈwiːzl/', N'chồn', 4),
(N'kangaroo', N'/ˌkæŋgəˈru/', N'con chuột túi', 4),
(N'hedgehog', N'/ˈhɛʤhɒg/', N'con nhím (ăn thịt)', 4),
(N'porcupine', N'/ˈpɔːkjʊpaɪn/', N'con nhím (ăn cỏ)', 4),
(N'gazelle', N'/gəˈzel/', N'linh dương gazen', 4),
(N'cheetah', N'/ˈtʃiː.tə/', N'báo gêpa', 4),
(N'gnu', N'/nuː/', N'linh dương đầu bò', 4),
(N'sheep', N'/ʃiːp/', N'cừu', 5),
(N'donkey', N'/ˈdɒŋki/', N'lừa', 5),
(N'goat', N'/gəʊt/', N'dê', 5),
(N'cow', N'/kaʊ/', N'bò', 5),
(N'buffalo', N'/ˈbʌfələʊ/', N'trâu', 5),
(N'goose /guːs/ ngỗng', N'/guːs/', N'ngỗng', 5),
(N'horse', N'/hɔːs/', N'ngựa', 5),
(N'dalf', N'/kæf/', N'bê con', 5),
(N'duck', N'/dʌk/', N'vịt', 5),
(N'drake', N'/dreɪk/', N'vịt đực', 5),
(N'duckling', N'/ˈdʌklɪŋ/', N'vịt con', 5),
(N'chicken', N'/ˈʧɪkɪn/', N'gà', 5),
(N'rooster /ˈruːstə/ gà trống', N'/ˈruːstə/', N'gà trống', 5),
(N'hen', N'/hɛn/', N'gà mái', 5),
(N'turkey', N'/ˈtɜːki/', N'gà tây', 5),
(N'piglet', N'/ˈpɪglət/', N'lợn con', 5),
(N'rabbit', N'/ˈræbɪt/', N'thỏ', 5),
(N'ox', N'/ɒks/', N'bò', 5),
(N'water buffalo', N'/ˈwɔːtə ˈbʌfələʊ/', N'trâu', 5),
(N'pig', N'/pɪg/', N'lợn', 5),
(N'bunny', N'/ˈbʌni/', N'thỏ con', 5),
(N'earthworm', N'/ɜːθ wɜːm/', N'giun đất', 5),
(N'cattle', N'/ˈkætl/', N'gia súc', 5),
(N'dog', N'', N'dɔːɡ chó đực', 5),
(N'puppy', N'/ˈpʌpi/', N'chó con', 5),
(N'queen', N'/kwiːn/', N'mèo cái', 5),
(N'kitten', N'/ˈkɪtn/', N'mèo con', 5),
(N'cat', N'/kæt/', N'mèo', 5),
(N'sheep', N'/ʃiːp/', N'con cừu', 5),
(N'dairy cow', N'/ˈdeə.ri kaʊ/', N'con bò sữa', 5),
(N'horses', N'/hɔːsiz/', N'con ngựa', 5),
(N'paѕture', N'/ˈpɑːѕ.tʃəʳ/', N'bãi ᴄhăn thả ᴠật nuôi', 5),
(N'farmer', N'/ˈfɑː.məʳ/', N'người nông dân, ᴄhủ trang trại', 5),
(N'barnуard', N'/ˈbɑːn.jɑːd/', N'ѕân nuôi gia ѕúc', 5),
(N'cattle', N'/ˈkæt.ļ/', N'(một đàn) gia ѕúᴄ', 5),
(N'coᴡboу', N'/ˈkaʊ.bɔɪ/', N'ᴄậu bé ᴄhăn bò', 5),
(N'coᴡgirl', N'/ˈkaʊ.gɜːl/', N'ᴄô gái ᴄhăn bò', 5),
(N'alligato', N'/ˈæl.ɪ.geɪ.təʳ/', N'r  cá sấu mỹ', 6),
(N'crocodile', N'/ˈkrɒk.ə.daɪl/', N'cá sấu', 6),
(N'toad', N'/təʊd/', N'con cóc', 6),
(N'frog', N'/frɒg/', N'con ếch', 6),
(N'dinosaurs', N'/’daɪnəʊsɔː/', N'khủng long', 6),
(N'cobra - fang', N'/ˈkəʊ.brə. fæŋ/', N'rắn hổ mang-răng nanh', 6),
(N'chameleon', N'/kəˈmiː.li.ən/', N'tắc kè hoa', 6),
(N'dragon', N'/ˈdræg.ən/', N'con rồng', 6),
(N'turtle-shell', N'/ˈtɜː.tl ʃel/', N'mai rùa', 6),
(N'lizard/', N'', N'ˈlɪz.əd thằn lằn', 6),
(N'ant', N'/ænt/', N'- con kiến', 7),
(N'fire ant', N'/faɪə ænt/', N'- kiến lửa', 7),
(N'rove beetle', N'/rəʊv biːtl/', N'- kiến ba khoang', 7),
(N'millipede', N'/ˈmɪləpiːd/', N'- con cuốn chiếu', 7),
(N'spider', N'/ˈspaɪ.dəʳ/', N'- nhện', 7),
(N'cocoon', N'/kəˈkuːn/', N'- kén', 7),
(N'aphid', N'/ˈeɪfɪd/', N'- con rệp cây', 7),
(N'centipede', N'/ˈsen.tɪ.piːd/', N'- con rết', 7),
(N'scorpion', N'/ˈskɔː.pi.ən/', N'- bọ cạp', 7),
(N'flea  /fliː/- con bọ chét', N'', N'', 7),
(N'slug', N'/slʌɡ/', N'- sên nhớt', 7),
(N'earthworm', N'/ˈɜːθ wɜːm/', N'- giun đất', 7),
(N'maggot', N'/ˈmæɡət/', N'- con giòi', 7),
(N'snail', N'/sneɪl/', N'- ốc sên', 7),
(N'tapeworm', N'/ˈteɪp wɜːm/', N'- sán dây', 7),
(N'hookworm', N'/hʊk wɜːm/', N'- giun móc', 7),
(N'large roundworm', N'/lɑːdʒ raʊnd wɜːm/', N'- giun đũa', 7),
(N'tick', N'/tɪk/', N'- con bọ ve', 7),
(N'louse', N'/laʊs/', N'- con rận', 7),
(N'caterpillar', N'/ˈkæt.ə.pɪl.əʳ/', N'- sâu bướm', 8),
(N'giant water bug', N'/ˈdʒaɪənt ˈwɔːtə bʌɡ/', N'- cà cuống', 8),
(N'stink bug', N'/stɪŋk bʌɡ/', N'- bọ xít', 8),
(N'cicada', N'/səˈkɑːdə/', N'- ve sầu', 8),
(N'butterfly', N'/ˈbʌt.ə.flaɪ/', N'- bướm', 8),
(N'moth', N'/mɒθ/', N'- bướm đêm, sâu bướm', 8),
(N'cockroach', N'/ˈkɒk.rəʊtʃ/', N'- con gián', 8),
(N'cricket', N'/ˈkrɪk.ɪt/', N'- con dế', 8),
(N'dragonfly', N'/ˈdrægən flaɪ/', N'- chuồn chuồn', 8),
(N'damselfly', N'/ˈdæmzəl flaɪ/', N'- chuồn chuồn kim', 8),
(N'bee', N'/biː/', N'- con ong', 8),
(N'wasp', N'/wɒsp/', N'- ong bắp cày', 8),
(N'firefly', N'/ˈfaɪə flaɪ/', N'- đom đóm', 8),
(N'fly', N'/flaɪz/', N'- con ruồi', 8),
(N'grasshopper', N'/ˈgrɑːsˌhɒp.əʳ/', N'- châu chấu', 8),
(N'termite', N'/ˈtɜː.maɪt/', N'- con mối', 8),
(N'mosquito', N'/məˈskiː.təʊ/', N'- con muỗi', 8),
(N'ladybug', N'/ˈleɪ.di.bɜːd/', N'- con bọ rùa', 8),
(N'scarab beetle', N'/ˈskærəb ˈbiː.tļ/', N'- bọ hung', 8),
(N'mantis', N'/ˈmæn.tɪs/', N'- con bọ ngựa', 8),
(N'beetle', N'/ˈbiː.tļ/', N'- bọ cánh cứng', 8);