services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA="Y"
    ports:
      - 1433:1433
    env_file:
      - .env
    
